### ISSUE TITLE
after installing and waking up with wake word, it gives error

### ISSUE THREAD

**Issue by oturan233** [LeonardSEO/MMM-VoiceCompanion#3]
[2024-09-11 13:56:41.807] [ERROR] Error processing audio: APIConnectionError: Connection error.
    at OpenAI.makeRequest (/home/ozgur/MagicMirror/modules/MMM-VoiceCompanion/node_modules/openai/core.js:304:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Class.transcribeAudio (/home/ozgur/MagicMirror/modules/MMM-VoiceCompanion/node_helper.js:162:31)
    at async Class.stopRecording (/home/ozgur/MagicMirror/modules/MMM-VoiceCompanion/node_helper.js:143:35)
    at async Class.listenForWakeWord (/home/ozgur/MagicMirror/modules/MMM-VoiceCompanion/node_helper.js:85:21) {
  status: undefined,
  headers: undefined,
  request_id: undefined,
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined,
  cause: FetchError: request to https://api.openai.com/v1/audio/transcriptions failed, reason: read ECONNRESET
      at ClientRequest.<anonymous> (/home/ozgur/MagicMirror/modules/MMM-VoiceCompanion/node_modules/node-fetch/lib/index.js:1501:11)
      at ClientRequest.emit (node:events:514:28)
      at ClientRequest.emit (node:domain:488:12)
      at TLSSocket.socketErrorListener (node:_http_client:495:9)
      at TLSSocket.emit (node:events:526:35)
      at TLSSocket.emit (node:domain:488:12)
      at emitErrorNT (node:internal/streams/destroy:151:8)
      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    type: 'system',
    errno: 'ECONNRESET',
    code: 'ECONNRESET'
  }
}

**Comment by slolson1** [comment]
I have the same issue

**Comment by LeonardSEO** [comment]
Sorry for the inactivity, it should be fixed now. Use the new config in the ReadME! If there are any issues again, please report them and I'll fix them right away! I'll try to be more active! Apologies
